version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip3 install -r mysite/requirements.txt
      - pip3 install pylint pytest

  pre_build:
    commands:
      - python3 --version
      - pylint --exit-zero $CODEBUILD_SRC_DIR/mysite/*.py
      - pylint --exit-zero $CODEBUILD_SRC_DIR/myapp/*.py
      # - pylint $CODEBUILD_SRC_DIR/job-portal/*.py --errors-only

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
