branch-defaults:
  default:
    environment: calorie-env
global:
  application_name: calorie_tracker
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
